[package]
name = "proxygen"
version = "0.1.0"
authors = ["Thomas Hansen <dryvnt@gmail.com>"]

[dependencies]
clippy = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
maud = "*"
maud_macros = "*"
lazy_static = "*"
regex = "*"
nickel = "*"
